.TH std::nested_exception::rethrow_nested 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   [[noreturn]] void rethrow_nested() const;  \fI(since C++11)\fP

   Rethrows the stored exception. If there is no stored exceptions (i.e. nested_ptr()
   returns null pointer), then std::terminate is called.

.SH Parameters

   \fI(none)\fP

.SH Return value

   \fI(none)\fP
