.TH std::promise::get_future 3 "Apr 19 2014" "1.0.0" "C++ Standard Libary"
.SH Synopsis
   std::future<R> get_future();  \fI(since C++11)\fP

   Returns a future object associated with the same shared state as *this.

   Exception is thrown if *this has no shared state or get_future has already been
   called.

.SH Parameters

   \fI(none)\fP

.SH Return value

   A future referring to the shared state of *this

.SH Exceptions

   std::future_error on the following conditions:

     * *this has no shared state. The error category is set to no_state.

     * get_future() has already been called on a promise with the same shared state as
       *this. The error category is set to future_already_retrieved.
